export const CREATE_TRANSECTION_REQUEST = 'CREATE_TRANSECTION_REQUEST'
export const CREATE_TRANSECTION_SUCCESS = 'CREATE_TRANSECTION_SUCCESS'
export const CREATE_TRANSECTION_FAIL = 'CREATE_TRANSECTION_FAIL'

export const ALL_TRANSECTION_REQUEST = 'ALL_TRANSECTION_REQUEST'
export const ALL_TRANSECTION_SUCCESS = 'ALL_TRANSECTION_SUCCESS'
export const ALL_TRANSECTION_FAIL = 'ALL_TRANSECTION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'